### PR TITLE
Implement String Validator with case option

### PR DESCRIPTION
**Pull request by rphilip457**
Implemented a string validator class with validation of case and normalisation. This included:
 - Camel Case
 - Upper Case
 - Lower Case
 - Normalisation (only letters or numbers).

### CODE REVIEW

**Review by Qoyyuum — APPROVED** [review]
Looks good

**Comment by jTaylo99** [comment]
Pretty happy with this! Just a small merge conflict and it should be good. Another small thing would be to check out the Google styleguide for function docstrings: https://google.github.io/styleguide/pyguide.html#s3.8.3-functions-and-methods
Your docstring is close but I think we should aim to keep to the Google styleguide as our standard.

**Comment by jTaylo99** [comment]
Accidently closed haha apologies

**Comment by jTaylo99** [comment]
Looks good! Merged.

**Pull request merged**
